services:
  # nextjs frontend service
  next:
    container_name: next
    image: next:1.0.0
    build:
      context: ./frontend
      dockerfile: next.dockerfile
    depends_on:
      - flask

  # flask service
  flask: 
    container_name: flask
    image: flask:1.0.0
    build: 
      context: ./backend
      dockerfile: flask.dockerfile
    ports:
      - 4000:4000

  